services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventario
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  backend:
    build: ./backend
    restart: always
    env_file:
      - ./backend/.env.example
    depends_on:
      - db
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/inventario
  frontend:
    build: ./frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
volumes:
  db_data:
